DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT
(
    ACCOUNT_ID   VARCHAR(255),
    NICK_NAME    VARCHAR(255),
    PASSWORD     VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    PRIMARY KEY (ACCOUNT_ID)
);